
package com.exo.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonneServiceWS", targetNamespace = "http://service.soap.exo.com/", wsdlLocation = "http://localhost:8999/PersonneServiceWS?wsdl")
public class PersonneServiceWS
    extends Service
{

    private final static URL PERSONNESERVICEWS_WSDL_LOCATION;
    private final static WebServiceException PERSONNESERVICEWS_EXCEPTION;
    private final static QName PERSONNESERVICEWS_QNAME = new QName("http://service.soap.exo.com/", "PersonneServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8999/PersonneServiceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONNESERVICEWS_WSDL_LOCATION = url;
        PERSONNESERVICEWS_EXCEPTION = e;
    }

    public PersonneServiceWS() {
        super(__getWsdlLocation(), PERSONNESERVICEWS_QNAME);
    }

    public PersonneServiceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONNESERVICEWS_QNAME, features);
    }

    public PersonneServiceWS(URL wsdlLocation) {
        super(wsdlLocation, PERSONNESERVICEWS_QNAME);
    }

    public PersonneServiceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONNESERVICEWS_QNAME, features);
    }

    public PersonneServiceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonneServiceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonneService
     */
    @WebEndpoint(name = "PersonneServicePort")
    public PersonneService getPersonneServicePort() {
        return super.getPort(new QName("http://service.soap.exo.com/", "PersonneServicePort"), PersonneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonneService
     */
    @WebEndpoint(name = "PersonneServicePort")
    public PersonneService getPersonneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.exo.com/", "PersonneServicePort"), PersonneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONNESERVICEWS_EXCEPTION!= null) {
            throw PERSONNESERVICEWS_EXCEPTION;
        }
        return PERSONNESERVICEWS_WSDL_LOCATION;
    }

}
